-- DOCTORS
INSERT INTO DOCTOR VALUES ('MR. X', 'CS', 1500);
INSERT INTO DOCTOR VALUES ('MR. Y', 'GS', 2000);
INSERT INTO DOCTOR VALUES ('MR. A', 'IM', 1000);
INSERT INTO DOCTOR VALUES ('MR. B', 'ER', 1200);
-- PATIENTS
INSERT INTO PATIENT VALUES ('P-101', 'A', 'DHK');
INSERT INTO PATIENT VALUES ('P-102', 'B', 'CTG');
INSERT INTO PATIENT VALUES ('P-103','C', 'SYL'); 
INSERT INTO PATIENT VALUES ( 'P-104', 'D', 'DHK');
-- APPOINTMENT_INFO
INSERT INTO APPOINTMENT_INFO VALUES('P-101','MR. X','CS','25-AUG-2023');
INSERT INTO APPOINTMENT_INFO VALUES('P-102','MR. Y','GS','26-AUG-2023');
INSERT INTO APPOINTMENT_INFO VALUES('P-103','MR. Z','IM','26-AUG-2023');
INSERT INTO APPOINTMENT_INFO VALUES('P-104','MR. A','ER','27-AUG-2023');
